import {
  Body,
  Controller,
  Get,
  HttpStatus,
  InternalServerErrorException,
  Post,
  UseGuards,
  ForbiddenException,
  Param,
} from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiNotFoundResponse,
  ApiResponse,
  ApiTags,
  ApiUnauthorizedResponse,
} from '@nestjs/swagger';
import { HttpService } from '@nestjs/axios';
import * as crypto from 'crypto';
import { catchError, firstValueFrom, map } from 'rxjs';
import { AxiosResponse } from '@nestjs/terminus/dist/health-indicator/http/axios.interfaces';
import * as dotenv from 'dotenv';
import { WalletGuard, HmacMiddleware } from '../guards';
import { ImpressionDto, RewardDto } from './dto';
import { RewardService } from './reward.service';
import impressionsJson from '../../../pool_impressions_example.json';
import { IPool } from '../../models';
dotenv.config();

@ApiTags('pools')
@Controller('pools')
export class PoolsController {
  constructor(
    private readonly rewardService: RewardService,
    private httpService: HttpService,
  ) {}

  @Get('joined/:address')
  @UseGuards(WalletGuard)
  @ApiBearerAuth('authorization')
  @ApiResponse({
    status: HttpStatus.OK,
    type: [RewardDto],
    description: 'Returns joined pools for a givven address',
  })
  async getJoined(@Param('address') address: string): Promise<IPool[]> {
    return this.rewardService.getJoinedPools(address);
  }

  @Post('impressions')
  @UseGuards(HmacMiddleware)
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'Returns 200 OK',
  })
  @ApiNotFoundResponse({ description: 'Endpoint not found' })
  @ApiUnauthorizedResponse({ description: 'You need a valid key' })
  public async saveImpressions(
    @Body() impressions: ImpressionDto[],
  ): Promise<void> {
    try {
      return await this.rewardService.saveImpressions(impressions);
    } catch (error) {
      throw new InternalServerErrorException(
        'Something went wrong. Please try again!',
      );
    }
  }

  // TODO - Remove this
  // THESE ARE FOR TESTING PURPOSES
  /*
    HMAC Authentication: HMAC (Hash-based Message Authentication Code) is a method of message authentication that uses a secret key to generate a message authentication code. 
    You could use HMAC to authenticate clients accessing your API.
    To implement this, you would generate a secret key and store it in your application's environment variables. 
    When a client makes a request to your API, they include a message authentication code (MAC) in the Authorization header of the request.
    The MAC is generated by hashing the request body or a portion of the request headers with the secret key.
    Your API then calculates the MAC using the same hashing algorithm and secret key, and verifies that it matches the MAC provided by the client.
    If the MACs match, your API grants access to the requested resource.
  */
  @Post('encrypt')
  async sendMessage() {
    const secretKey = process.env.GS_SECRET; // Get the secret key from environment variables
    // console.log('secret key: ', crypto.randomBytes(16).toString('hex'));
    console.log('Secret key:', secretKey);
    const hmac = crypto.createHmac('sha256', secretKey);
    hmac.update(Buffer.from(JSON.stringify(impressionsJson), 'utf-8')); // Hash the message with the secret key
    const digest = hmac.digest('hex'); // Generate the HMAC digest

    const headers = {
      Authorization: `HMAC ${digest}`,
    };

    return firstValueFrom(
      this.httpService
        .post('http://localhost:3040/pools/impressions', impressionsJson, {
          headers,
        })
        .pipe(
          map((res: AxiosResponse) => {
            console.log(res.data);
            return res.data;
          }),
          catchError((error) => {
            console.log(error);
            throw new ForbiddenException('API not available');
          }),
        ),
    );
  }

  @Post('decrypt')
  @UseGuards(HmacMiddleware)
  public async receiveMessage(@Body() body: ImpressionDto[]) {
    return body;
  }
}
